name: gti_website
description: "Web Application for GTI"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  carousel_slider: ^5.1.1
  flutter:
    sdk: flutter
  go_router: ^15.1.2
  video_player: ^2.9.5
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/gti_logo.png
    - assets/gti_logo_2.png
    - assets/sabg.png
    - assets/schoolautomate.png
    - assets/verify.png
    - assets/clientchart.png
    - assets/contact.jpg

    - assets/carousel_media/vid1.mp4
    - assets/carousel_media/1.jpg
    - assets/carousel_media/2.jpg
    - assets/carousel_media/3.jpg

    - assets/list_of_services/icon1.png
    - assets/list_of_services/icon2.png
    - assets/list_of_services/icon3.png
    - assets/list_of_services/icon4.png
    - assets/list_of_services/icon5.png
    - assets/list_of_services/icon6.png
    - assets/list_of_services/icon7.png
    - assets/list_of_services/icon8.png
    - assets/list_of_services/icon9.png
    - assets/list_of_services/icon10.png
    - assets/list_of_services/icon11.png

    - assets/gti_sofware_brings/icon1.png
    - assets/gti_sofware_brings/icon2.png
    - assets/gti_sofware_brings/icon3.png
    - assets/gti_sofware_brings/icon4.png
    - assets/gti_sofware_brings/icon5.png
    - assets/gti_sofware_brings/icon6.png

    - assets/business_boosting/icon1.png
    - assets/business_boosting/icon2.png
    - assets/business_boosting/icon3.png
    - assets/business_boosting/icon4.png

    - assets/client_logos/BFH.png
    - assets/client_logos/CHST.png
    - assets/client_logos/HSA.png
    - assets/client_logos/HSS.png
    - assets/client_logos/HTC.png
    - assets/client_logos/JCFC.png
    - assets/client_logos/LCCB.png
    - assets/client_logos/LCUP.png
    - assets/client_logos/LDCU.png
    - assets/client_logos/LSU.png
    - assets/client_logos/MPCF.png
    - assets/client_logos/SBC.jpeg
    - assets/client_logos/STIWNU.png
    - assets/client_logos/VMUF.png
    - assets/client_logos/WUPA.png
    - assets/client_logos/WUPC.png


  
  uses-material-design: true
