name: gti_website
description: "Web Application for GTI"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  carousel_slider: ^5.1.1
  flutter:
    sdk: flutter
  go_router: ^15.1.2
  video_player: ^2.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/gti_logo.png
    - assets/gti_logo_2.png
    - assets/carousel_media/vid1.mp4
    - assets/carousel_media/1.jpg
    - assets/carousel_media/2.jpg
    - assets/carousel_media/3.jpg
  
  uses-material-design: true
